set wrap
syntax on
set ruler
set number
set hlsearch
set t_Co=256
set tabstop=4
set expandtab
set autoindent
set lazyredraw
set backspace=2
set shiftwidth=4
set laststatus=2 
set textwidth=79
set guioptions-=L
set guioptions-=r
set guioptions-=m
set guioptions-=T
set encoding=utf-8
set background=dark
colorscheme solarized
set lines=36 columns=128
let g:solarized_termtrans=1
let g:solarized_termcolors=256
let g:airline_powerline_fonts=1
set guifont=DejaVu_Sans_Mono_for_Powerline:h14:cANSI:qDRAFT
